//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_UP.ModeloEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auditoria
    {
        public int AuditoriaID { get; set; }
        public string Usuario { get; set; }
        public string Accion { get; set; }
        public string Tabla { get; set; }
        public Nullable<int> RegistroID { get; set; }
        public Nullable<System.DateTime> FechaAccion { get; set; }
    }
}
