//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_UP.ModeloEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleados
    {
        public int EmpleadoID { get; set; }
        public string Nombre { get; set; }
        public int DepartamentoID { get; set; }
        public int CargoID { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public decimal SueldoBruto { get; set; }
        public bool Estado { get; set; }
        public byte[] FotoEmpleado { get; set; }
        public string ExtensionImagen { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<decimal> AFP { get; set; }
        public Nullable<decimal> ARS { get; set; }
        public Nullable<decimal> ISR { get; set; }
        public Nullable<decimal> TotalDescuentos { get; set; }
        public Nullable<decimal> SueldoNeto { get; set; }
        public string TiempoEnEmpresa { get; set; }
    
        public virtual Cargo Cargo { get; set; }
        public virtual Departamento Departamento { get; set; }
    }
}
