//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_UP.ModeloEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public int UsuarioID { get; set; }
        public string NombreUsuario { get; set; }
        public string Clave { get; set; }
        public int RolID { get; set; }
    
        public virtual Roles Roles { get; set; }
    }
}
